import streamlit as st

# Title
st.title('Investment Strategy Analysis Dashboard')

# Introduction
st.write("""
### Introduction
In this analysis, I delve into the risk and return characteristics of various investment strategies and portfolios. Utilizing a comprehensive suite of metrics, I assess and compare the performance of two systematic trading strategies (Series 1 and Series 2) and explore the integration of alternative indices within a traditional 60/40 equity/bond portfolio. My analysis, powered by Python, is visualized through this interactive Streamlit dashboard, offering dynamic insights based on user-selected parameters.
""")

# Metrics Employed
st.header('Metrics Employed')
st.write("""
I've leveraged an array of metrics to dissect and compare investment strategies on various fronts. These metrics are categorized under profitability, risk, and performance assessment to facilitate a nuanced understanding of each investment's characteristics.
""")

## Profitability
st.subheader('Profitability')
st.write("""
- **Geometric Mean Return:** Measures the average earnings from an investment, indicating its ability to generate profit over the selected period.
- **Cumulative Returns:** Captures the total percentage return generated by an investment over time, showcasing its overall profitability.
- **Annualized Return:** Provides the yearly average return, allowing for the comparison of investments over different time spans.
""")

## Volatility and Risk
st.subheader('Volatility and Risk')
st.write("""
- **Standard Deviation:** Quantifies the variability or dispersion of returns, reflecting the investment's volatility and inherent risk.
- **Annualized Volatility:** Offers a yearly perspective on the investment's volatility, aiding in understanding its risk over an extended period.
- **Maximum Drawdown:** Highlights the largest percentage drop from a peak to a trough, offering insight into potential loss and downside risk.
- **Value at Risk (VaR) and Conditional Value at Risk (CVaR):** Estimate the potential for loss in an investment, with VaR indicating the maximum expected loss over a specific period at a given confidence level, and CVaR providing the expected loss exceeding the VaR threshold.
""")

## Risk-Adjusted Performance
st.subheader('Risk-Adjusted Performance')
st.write("""
- **Sharpe Ratio:** Evaluates how well the return of an asset compensates the investor for the risk taken, with higher values indicating better risk-adjusted returns.
- **Sortino Ratio:** Similar to the Sharpe Ratio but focuses solely on downside volatility, offering a more nuanced view of risk-adjusted performance.
""")

# Dynamic Features
st.header('Dynamic Features')
st.write("""
My dashboard allows users to tailor the analysis through three adjustable parameters:
- **Date Range:** Selects the time frame for analysis.
- **Confidence Level:** Sets the confidence level for VaR and CVaR calculations.
- **Interest Rate:** Chooses the appropriate risk-free rate from the current rates of 13-week US Treasury Bills, 5-year Notes, 10-year Notes, and 30-year Bonds, updated daily via Yahoo Finance.
""")

# Visualization Tools
st.header('Visualization Tools')
st.write("""
I employ ECharts for dynamic and interactive charting, alongside AgGrid for table presentations, enhancing the user experience with versatile data exploration capabilities.
""")

# Analysis Conclusions
st.header('Analysis Conclusions')
st.write("""
**Part 1:** Based on the applied metrics, Series 2 outperforms Series 1 in risk and return characteristics.

**Part 2:** Among 23 tested combinations, allocating 60% to the S&P 500 Total Return Index and 40% to the CTA Index yields the best overall performance across all metrics, considering a 95% confidence level and a 4.44% risk-free rate.
""")

# Future Enhancements
st.header('Future Enhancements')
st.write("""
Further refinement of my analysis could include additional metrics such as Alpha, Beta, and Skewness. These enhancements would deepen our understanding of each investment's risk and return profile.
""")

